Improve Docker images usability (#249)
* Address import error encountered in annotation.ipynb

When trying to run `sc.pp.highly_variable_genes()` in
docs/tutorials/annotation.ipynb the following ImportError is encountered:

ImportError: Please install skmisc package via `pip install --user scikit-misc

Looking at the pyproject.toml for the `scanpy` project it looks like
the `scikit-misc` package can be co-installed by specifying
`scanpy[skmisc]` (see:
https://github.com/scverse/scanpy/blob/a956fa781a8406fc5030093356c0372456d9184b/pyproject.toml#L142)

* Make recommend-interactive docker image even more user friendly

User friendliness improvements:
- Added short guide on how to make use of Nvidia GPU with Docker image
- Updated recommend-interactive image and example command so that
  downloaded datasets can be shared with local machine (and vice versa)

- This commit also bumps the default `SnapATAC2` version that will
  be built when following the README to v2.6.0.

* Add guide sections for running SnapATAC2 Docker image on other platforms

* Fix formatting error in Docker README.md